//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_Asociados_CA.Server_Asociados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="estados", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class estados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="municipios", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class municipios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="localidades", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class localidades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userLogin", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class userLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoUsuarioField, value) != true)) {
                    this.tipoUsuarioField = value;
                    this.RaisePropertyChanged("tipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getSocioByNoSocio", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class getSocioByNoSocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable socioTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numSocio {
            get {
                return this.numSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.numSocioField, value) != true)) {
                    this.numSocioField = value;
                    this.RaisePropertyChanged("numSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable socioTab {
            get {
                return this.socioTabField;
            }
            set {
                if ((object.ReferenceEquals(this.socioTabField, value) != true)) {
                    this.socioTabField = value;
                    this.RaisePropertyChanged("socioTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="socio", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class socio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anioJubilacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string curpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noImmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreCompletoEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoSangreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anioJubilacion {
            get {
                return this.anioJubilacionField;
            }
            set {
                if ((object.ReferenceEquals(this.anioJubilacionField, value) != true)) {
                    this.anioJubilacionField = value;
                    this.RaisePropertyChanged("anioJubilacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMaternoField, value) != true)) {
                    this.apellidoMaternoField = value;
                    this.RaisePropertyChanged("apellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPaternoField, value) != true)) {
                    this.apellidoPaternoField = value;
                    this.RaisePropertyChanged("apellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                if ((object.ReferenceEquals(this.curpField, value) != true)) {
                    this.curpField = value;
                    this.RaisePropertyChanged("curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccionE {
            get {
                return this.direccionEField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionEField, value) != true)) {
                    this.direccionEField = value;
                    this.RaisePropertyChanged("direccionE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoCivilField, value) != true)) {
                    this.estadoCivilField = value;
                    this.RaisePropertyChanged("estadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.estatusField, value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoPerfilField, value) != true)) {
                    this.fotoPerfilField = value;
                    this.RaisePropertyChanged("fotoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                if ((this.idDireccionField.Equals(value) != true)) {
                    this.idDireccionField = value;
                    this.RaisePropertyChanged("idDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noImms {
            get {
                return this.noImmsField;
            }
            set {
                if ((object.ReferenceEquals(this.noImmsField, value) != true)) {
                    this.noImmsField = value;
                    this.RaisePropertyChanged("noImms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noSocio {
            get {
                return this.noSocioField;
            }
            set {
                if ((object.ReferenceEquals(this.noSocioField, value) != true)) {
                    this.noSocioField = value;
                    this.RaisePropertyChanged("noSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCompletoE {
            get {
                return this.nombreCompletoEField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreCompletoEField, value) != true)) {
                    this.nombreCompletoEField = value;
                    this.RaisePropertyChanged("nombreCompletoE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoE {
            get {
                return this.telefonoEField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoEField, value) != true)) {
                    this.telefonoEField = value;
                    this.RaisePropertyChanged("telefonoE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoSangre {
            get {
                return this.tipoSangreField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoSangreField, value) != true)) {
                    this.tipoSangreField = value;
                    this.RaisePropertyChanged("tipoSangre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mostrarSocios", Namespace="http://schemas.datacontract.org/2004/07/Server_Asociados_Jubilados_CA")]
    [System.SerializableAttribute()]
    public partial class mostrarSocios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable SocioTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable SocioTab {
            get {
                return this.SocioTabField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioTabField, value) != true)) {
                    this.SocioTabField = value;
                    this.RaisePropertyChanged("SocioTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server_Asociados.IServerAsociados")]
    public interface IServerAsociados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboEstados", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboEstadosResponse")]
        Cliente_Asociados_CA.Server_Asociados.estados[] cargarComboEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboEstados", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboEstadosResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.estados[]> cargarComboEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboMunicipios", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboMunicipiosResponse")]
        Cliente_Asociados_CA.Server_Asociados.municipios[] cargarComboMunicipios(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboMunicipios", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboMunicipiosResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.municipios[]> cargarComboMunicipiosAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboLocalidades", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboLocalidadesResponse")]
        Cliente_Asociados_CA.Server_Asociados.localidades[] cargarComboLocalidades(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/cargarComboLocalidades", ReplyAction="http://tempuri.org/IServerAsociados/cargarComboLocalidadesResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.localidades[]> cargarComboLocalidadesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/registrarLogin", ReplyAction="http://tempuri.org/IServerAsociados/registrarLoginResponse")]
        Cliente_Asociados_CA.Server_Asociados.userLogin registrarLogin(string nombreUsuario, string contrasenia, string tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/registrarLogin", ReplyAction="http://tempuri.org/IServerAsociados/registrarLoginResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.userLogin> registrarLoginAsync(string nombreUsuario, string contrasenia, string tipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/getBynoSocio", ReplyAction="http://tempuri.org/IServerAsociados/getBynoSocioResponse")]
        Cliente_Asociados_CA.Server_Asociados.getSocioByNoSocio getBynoSocio(string numSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/getBynoSocio", ReplyAction="http://tempuri.org/IServerAsociados/getBynoSocioResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.getSocioByNoSocio> getBynoSocioAsync(string numSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/registrarSocio", ReplyAction="http://tempuri.org/IServerAsociados/registrarSocioResponse")]
        Cliente_Asociados_CA.Server_Asociados.socio registrarSocio(
                    int idSocio, 
                    string noSocio, 
                    string nombre, 
                    string apellidoPaterno, 
                    string apellidoMaterno, 
                    System.DateTime fechaNacimiento, 
                    int edad, 
                    string celular, 
                    string telefono, 
                    string anioJubilacion, 
                    string estadoCivil, 
                    string tipoSangre, 
                    string noImms, 
                    string curp, 
                    int idDireccion, 
                    byte[] fotoPerfil, 
                    string nombreCompletoE, 
                    string direccionE, 
                    string telefonoE, 
                    string estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/registrarSocio", ReplyAction="http://tempuri.org/IServerAsociados/registrarSocioResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.socio> registrarSocioAsync(
                    int idSocio, 
                    string noSocio, 
                    string nombre, 
                    string apellidoPaterno, 
                    string apellidoMaterno, 
                    System.DateTime fechaNacimiento, 
                    int edad, 
                    string celular, 
                    string telefono, 
                    string anioJubilacion, 
                    string estadoCivil, 
                    string tipoSangre, 
                    string noImms, 
                    string curp, 
                    int idDireccion, 
                    byte[] fotoPerfil, 
                    string nombreCompletoE, 
                    string direccionE, 
                    string telefonoE, 
                    string estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/getSocio", ReplyAction="http://tempuri.org/IServerAsociados/getSocioResponse")]
        Cliente_Asociados_CA.Server_Asociados.mostrarSocios getSocio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerAsociados/getSocio", ReplyAction="http://tempuri.org/IServerAsociados/getSocioResponse")]
        System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.mostrarSocios> getSocioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerAsociadosChannel : Cliente_Asociados_CA.Server_Asociados.IServerAsociados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerAsociadosClient : System.ServiceModel.ClientBase<Cliente_Asociados_CA.Server_Asociados.IServerAsociados>, Cliente_Asociados_CA.Server_Asociados.IServerAsociados {
        
        public ServerAsociadosClient() {
        }
        
        public ServerAsociadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerAsociadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerAsociadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerAsociadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente_Asociados_CA.Server_Asociados.estados[] cargarComboEstados() {
            return base.Channel.cargarComboEstados();
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.estados[]> cargarComboEstadosAsync() {
            return base.Channel.cargarComboEstadosAsync();
        }
        
        public Cliente_Asociados_CA.Server_Asociados.municipios[] cargarComboMunicipios(int id) {
            return base.Channel.cargarComboMunicipios(id);
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.municipios[]> cargarComboMunicipiosAsync(int id) {
            return base.Channel.cargarComboMunicipiosAsync(id);
        }
        
        public Cliente_Asociados_CA.Server_Asociados.localidades[] cargarComboLocalidades(int id) {
            return base.Channel.cargarComboLocalidades(id);
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.localidades[]> cargarComboLocalidadesAsync(int id) {
            return base.Channel.cargarComboLocalidadesAsync(id);
        }
        
        public Cliente_Asociados_CA.Server_Asociados.userLogin registrarLogin(string nombreUsuario, string contrasenia, string tipoUsuario) {
            return base.Channel.registrarLogin(nombreUsuario, contrasenia, tipoUsuario);
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.userLogin> registrarLoginAsync(string nombreUsuario, string contrasenia, string tipoUsuario) {
            return base.Channel.registrarLoginAsync(nombreUsuario, contrasenia, tipoUsuario);
        }
        
        public Cliente_Asociados_CA.Server_Asociados.getSocioByNoSocio getBynoSocio(string numSocio) {
            return base.Channel.getBynoSocio(numSocio);
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.getSocioByNoSocio> getBynoSocioAsync(string numSocio) {
            return base.Channel.getBynoSocioAsync(numSocio);
        }
        
        public Cliente_Asociados_CA.Server_Asociados.socio registrarSocio(
                    int idSocio, 
                    string noSocio, 
                    string nombre, 
                    string apellidoPaterno, 
                    string apellidoMaterno, 
                    System.DateTime fechaNacimiento, 
                    int edad, 
                    string celular, 
                    string telefono, 
                    string anioJubilacion, 
                    string estadoCivil, 
                    string tipoSangre, 
                    string noImms, 
                    string curp, 
                    int idDireccion, 
                    byte[] fotoPerfil, 
                    string nombreCompletoE, 
                    string direccionE, 
                    string telefonoE, 
                    string estatus) {
            return base.Channel.registrarSocio(idSocio, noSocio, nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, edad, celular, telefono, anioJubilacion, estadoCivil, tipoSangre, noImms, curp, idDireccion, fotoPerfil, nombreCompletoE, direccionE, telefonoE, estatus);
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.socio> registrarSocioAsync(
                    int idSocio, 
                    string noSocio, 
                    string nombre, 
                    string apellidoPaterno, 
                    string apellidoMaterno, 
                    System.DateTime fechaNacimiento, 
                    int edad, 
                    string celular, 
                    string telefono, 
                    string anioJubilacion, 
                    string estadoCivil, 
                    string tipoSangre, 
                    string noImms, 
                    string curp, 
                    int idDireccion, 
                    byte[] fotoPerfil, 
                    string nombreCompletoE, 
                    string direccionE, 
                    string telefonoE, 
                    string estatus) {
            return base.Channel.registrarSocioAsync(idSocio, noSocio, nombre, apellidoPaterno, apellidoMaterno, fechaNacimiento, edad, celular, telefono, anioJubilacion, estadoCivil, tipoSangre, noImms, curp, idDireccion, fotoPerfil, nombreCompletoE, direccionE, telefonoE, estatus);
        }
        
        public Cliente_Asociados_CA.Server_Asociados.mostrarSocios getSocio() {
            return base.Channel.getSocio();
        }
        
        public System.Threading.Tasks.Task<Cliente_Asociados_CA.Server_Asociados.mostrarSocios> getSocioAsync() {
            return base.Channel.getSocioAsync();
        }
    }
}
